### ISSUE TITLE
Crash when using `--squash-uids` flag

### ISSUE THREAD

**Issue by edubart** [cartesi/genext2fs#2]
I had a script that used `--squash-uids` flag, and it is not working anymore with this `genext2fs`.

```
genext2fs --squash-uids
Segmentation fault (core dumped)
```

While the original don't have this issue:

```
/usr/bin/genext2fs --squash-uids
/usr/bin/genext2fs: Not enough arguments. Try --help or else see the man page.
```

**Comment by edubart** [comment]
I noticed that that `--squash-uids` requires a new argument, I tried using like `--squash-uids 0` but it also crashes.
I think passing a uid should have been optional, so we don't break usage of scripts that already used to work with old genext2fs version.

`--squash` does not seems to work either.

**Comment by mpolitzer** [comment]
Long option is indeed broken, use `-U` for now.
